### ISSUE TITLE
GitHub Api

### ISSUE THREAD

**Issue by Marzocchi666** [kubernetes/kube-proxy#11]
Hello, i want to make a request to github to get the latest version of kube-proyx. Could you please set the tag to latest version please? The request wont work unless i specify a specific release ID. Is it possible to make it the same as coredns? https://github.com/coredns/coredns/releases

P.S: Not sure if this is an issue but didnt know where else to ask this. It would be nice tough. TYTY

Thank you,
Mzch.

**Comment by nikhita** [comment]
It's unfortunately controlled by GitHub. :(

https://github.com/kubernetes/client-go/issues/961 has more context on the issue. Going to close this as a duplicate of https://github.com/kubernetes/client-go/issues/961 to consolidate all discussions at one place.
