### ISSUE TITLE
IPVS mode: traffic sent from pods to an external LoadBalancer IP is NOT directed to the respective cluster IP instead

### ISSUE THREAD

**Issue by amorozkin** [kubernetes/kube-proxy#18]
But, if I'm not mistaken, according to [docs ](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/#:~:text=will%20be%20masqueraded%20and-,traffic%20sent%20from%20pods%20to%20an%20external%20LoadBalancer%20IP%20will%20be%20directed%20to%20the%20respective%20cluster%20IP%20instead.,-For%20dual)it do should to.

kube-proxy:v1.23.4

**Comment by sftim** [comment]
Let's close this. If it turns out that this is the right repo, we can get Prow to move https://github.com/kubernetes/kubernetes/issues/115931 into this repo.

**Comment by danwinship** [comment]
> As I'm not sure picking the tight repo for the issue - here is the duplicate I've just posted to main repo - [kubernetes/kubernetes#115931](https://github.com/kubernetes/kubernetes/issues/115931)

yeah, k/k is the right repo
