### ISSUE TITLE
UDP Load Balancing Not Working in 1.19.x

### ISSUE THREAD

**Issue by icpenguins** [kubernetes/kube-proxy#9]
I recently upgraded to Kubernetes 1.19.0. The upgrade said it was completed successfully. The configuration was working as expected before the upgrade.

I saw no traffic getting load-balanced. I then upgraded flannel to quay.io/coreos/flannel:v0.13.0-rc2. I rebooted the entire cluster after the upgrade. I see no load-balanced traffic for a UDP service.

I then upgraded to Kubernetes 1.19.2 and re-applied the MetalLB manifest. I have seen no change and continue to see no load-balancing and all load is going to the master node.

I found a link in Kubernetes for someone else who had an issue with the 1.19 upgrade, although it appeared to resolve itself after a reboot (link [Source IP Not Preserved](https://github.com/kubernetes/kubernetes/issues/94563))

I opened a support ticket with MetalLB, but they truly don't believe it has anything to do with them. They pointed me at my router manufacturer, Ubiquiti EdgeOS to determine the next steps.

[MetalLB Issue 720](https://github.com/metallb/metallb/issues/720)

I reached out to Ubiquiti's community and, for the most part, believe that they are at least doing round-robin packet forwarding. This could be an issue and would generally create dropped packets. However, I do not see that either.

[BGP Load Balancing in EdgeOS...](https://community.ui.com/questions/BGP-Load-Balancing-in-EdgeOS-Not-Working/e337f8b8-bda8-43f5-aefe-f85b20248786)

After this, I have completely pulled down my K8s cluster and rebuilt it from scratch. I have implemented Calico now, instead of MetalLB, to announce the BGP routes. All routes are working correctly and, with Calico, I can now see both Cluster Service IP addresses remotely and External IPs.

Now, I still see the same behavior where the External IP does not load balance traffic in any fashion. However, if I used the Cluster Service IP from a remote host, I get correct load balancing behavior, but then lose the source IP address. The configuration for the service is to have `externalTrafficPolicy: Local`. According to this configuration, I should have the source IP of the remote requestor.

All my configurations and debugging details are in the two different issues I've raised, but happy to add them here if someone would find them useful.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: syslog-forwarder
  labels:
    app: redacted
  namespace: redacted
spec:
  selector:
    app: redacted
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
  - 10.2.1.15
  clusterIP: 10.96.0.15
  ports:
  - port: 5140
    targetPort: 5140
    protocol: UDP
    name: unifi
  - port: 5142
    targetPort: 5142
    protocol: UDP
    name: edgemax
```

```bash
redacted@ER-4:~$ ip r
10.0.0.0/16 dev bond0.1000 proto kernel scope link src 10.0.0.1
10.0.0.1 dev lo proto kernel scope link
10.1.84.128/26 via 10.0.0.12 dev bond0.1000 proto zebra
10.1.182.192/26 via 10.0.0.11 dev bond0.1000 proto zebra
10.1.235.192/26 via 10.0.0.10 dev bond0.1000 proto zebra
10.2.0.0/24 proto zebra
        nexthop via 10.0.0.12  dev bond0.1000 weight 1
        nexthop via 10.0.0.11  dev bond0.1000 weight 1
        nexthop via 10.0.0.10  dev bond0.1000 weight 1
10.2.1.0/24 proto zebra
        nexthop via 10.0.0.12  dev bond0.1000 weight 1
        nexthop via 10.0.0.11  dev bond0.1000 weight 1
        nexthop via 10.0.0.10  dev bond0.1000 weight 1
10.2.1.15 proto zebra
        nexthop via 10.0.0.12  dev bond0.1000 weight 1
        nexthop via 10.0.0.11  dev bond0.1000 weight 1
        nexthop via 10.0.0.10  dev bond0.1000 weight 1
10.96.0.0/12 proto zebra
        nexthop via 10.0.0.12  dev bond0.1000 weight 1
        nexthop via 10.0.0.11  dev bond0.1000 weight 1
        nexthop via 10.0.0.10  dev bond0.1000 weight 1
10.96.0.15 proto zebra
        nexthop via 10.0.0.12  dev bond0.1000 weight 1
        nexthop via 10.0.0.11  dev bond0.1000 weight 1
        nexthop via 10.0.0.10  dev bond0.1000 weight 1
10.104.196.173 proto zebra
        nexthop via 10.0.0.12  dev bond0.1000 weight 1
        nexthop via 10.0.0.11  dev bond0.1000 weight 1
... redacted
```

**Comment by rikatz** [comment]
Per CONTRIBUTING.md, please open this issue at kubernetes/kubernetes repo, this repository is a read-only and people usually don't watch it :)

/close
